RISCV_PREFIX   ?= riscv32-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_GCC_OPTS ?= -static -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES) -march=rv32i_zicsr

COMPILE_CMD = $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) -I$(ROOTDIR)/riscv-test-suite/env/ -I$(TARGETDIR)/$(RISCV_TARGET)/ -T$(TARGETDIR)/$(RISCV_TARGET)/env/linkmono.ld $$< -o $$@; $$(RISCV_OBJCOPY) -O binary $$@ $$@.bin

OBJ_CMD = $$(RISCV_OBJDUMP) $$@ --source > $$@.debug

COMPILE_TARGET = $(COMPILE_CMD); $(OBJ_CMD)

RUN_TARGET =