include ../common/common.mk

.PHONY: run all clean

run all:
	@echo "wave-generator has no local assembly sources to build"
	@false

clean:
	@rm -f out.leaf.elf out.leaf.bin out.leaf.debug out.leaf.dump
	@rm -f out.spike.elf out.spike.bin out.spike.debug out.spike.signature
